In [1]:
import numpy as np
import matplotlib as plt

In [2]:

# Question 3
##############################################################################################
# Part (a)

matrixA = np.array([[0.8, 0.0, 0.0, 0.05, 0.15],
                   [1.0, 0.0, 0.0, 0.0, 0.0],
                   [0.3, 0.2, 0.5, 0.0, 0.0],
                   [0.0, 0.0, 0.05, 0.95, 0.0],
                   [0.0, 0.0, 0.0, 0.2, 0.8]])

# Print matrix to make sure its been intialzed correctly.
print("Matrix A:\n",matrixA)

# Check that each rows coumn values add up to one.
for row in matrixA:
    sum_acum = 0
    for col in row:
        sum_acum += col
    if sum_acum  == 1:
        # print("Stochastic!")
        continue
    else:
        print(f"Not stocahstic at with this {row}")
        break

Matrix A:
 [[0.8  0.   0.   0.05 0.15]
 [1.   0.   0.   0.   0.  ]
 [0.3  0.2  0.5  0.   0.  ]
 [0.   0.   0.05 0.95 0.  ]
 [0.   0.   0.   0.2  0.8 ]]


In [3]:
# Question 3
##############################################################################################
# Part (b)

# Intialize opnion vector
opnionVector = np.array([[1], [1], [0.5], [0], [0]])

# Verify initialized opnion matrix 
print("Opnion Matrix:\n", opnionVector)

# Perform matrix multiplication
matrixProduct = matrixA @ opnionVector

# Print to verify matrix mutliplication was done correctly by hand
print("Matrix Mulitplication Output:\n", matrixProduct)

Opnion Matrix:
 [[1. ]
 [1. ]
 [0.5]
 [0. ]
 [0. ]]
Matrix Mulitplication Output:
 [[0.8  ]
 [1.   ]
 [0.75 ]
 [0.025]
 [0.   ]]


In [4]:
# Question 3
##############################################################################################
# Part (c)
# Perfrom matrix multiplication to show how values converge. 
print("Matrix as \'t\' Approaches Inifinity:\n", np.linalg.matrix_power(matrixA,100000))

Matrix as 't' Approaches Inifinity:
 [[0.16051364 0.01284109 0.06420546 0.64205457 0.12038523]
 [0.16051364 0.01284109 0.06420546 0.64205457 0.12038523]
 [0.16051364 0.01284109 0.06420546 0.64205457 0.12038523]
 [0.16051364 0.01284109 0.06420546 0.64205457 0.12038523]
 [0.16051364 0.01284109 0.06420546 0.64205457 0.12038523]]


In [8]:
# Question 4
##############################################################################################
# Part (a)

# This represnt the first part of the equations which is the sumation of elements in the matrix 
# from the beging step to the range of t specified steps.
def compute_series(Lam, A, t):
    n = A.shape[0]
    accum = np.zeros(n, n)
    for i in range(t):
        accum += np.linalg.matrix_power(Lam@A, i)
    return accum

def friedkin_johnson(Lam, A, x0, t, plot_result = False):
    n = A.shape[0] # assuming everything is dimensioned right
    I = np.eye(n)
    xx = np.zeros((n,t))
    xx[:,0] = x0
    for i in range(1,t) :
      print(F"Lambda Diag Matrix:\n{Lam}")
      print(f"Adjacenty Matrix:\n{A}")
      print(f"Lambda Diag Matrix @ Adjacenty Matrix = \n{Lam@A}")
      print(f"Last opnion vector:\n{xx[:,i-1]}")
      print(f"Lambda Diag Matrix @ Adjacenty Matrix @ Last opnion vector =\n{Lam@A@xx[:,i-1]}")
      print(f"Identity Matrix: \n{I}")
      print(f"Invers of Lam:\n{I - Lam}")
      print(f"Initial Opnion:\n{x0}")
      print(f"(I - Lam)@x0 = {(I-Lam)@x0}")
      print(f"Finally we take the sum of { Lam@A@xx[:,i-1]} + {(I-Lam)@x0} = \n{Lam@A@xx[:,i-1] + (I-Lam)@x0}")
      xx[:,i] = Lam@A@xx[:,i-1] + (I-Lam)@x0
    if plot_result:
      plt.plot(xx.T)
    return xx 

# Create power constant for simulation runs
k = 1

# Initalize matrix from question 2
matrixB = np.array([[0.25, 0.5, 0.0, 0.025],
                    [0.3, 0.3, 0.3,  0],
                    [0.0, 0.0, 0.1, 0.0],
                    [0.0, 0.25, 0, 0.75]])

# Initialize given lambda values for the question
lambdas = [0.9, 0.1, 0.9, 0.1] 

# Initialize given original opnions
opnionVectorB = np.array([0.9, 0.1, 0.9, 0.1])
 
# Get the diagnoal matrix of lambda values 
matrixDiag = np.diag(lambdas)

# print(f"{matrixDiag} .{matrixB} = {matrixDiag @ matrixB}")
# print(matrixDiag @ matrixB )

# print("Matrix of diagonal lambda values:")
# print(matrixDiag)

# print(matrixB@matrixDiag)
# # Show that our valeus will quickly converge and envetually get very close to 0, but not quite
# # python ends up rounding to 0 after so long due to not being able to retain decmials values.
# print(f"Matrixed rasied to the \'k-th\' ({k}):")
# print(np.linalg.matrix_power(matrixB@matrixDiag, k))

# Now using method created above we perform the first of the Freidken Johnson modle
print("Executing first step of Friedkin-Johnson model:\n", friedkin_johnson(matrixDiag, matrixB, opnionVectorB, 2))

Lambda Diag Matrix:
[[0.9 0.  0.  0. ]
 [0.  0.1 0.  0. ]
 [0.  0.  0.9 0. ]
 [0.  0.  0.  0.1]]
Adjacenty Matrix:
[[0.25  0.5   0.    0.025]
 [0.3   0.3   0.3   0.   ]
 [0.    0.    0.1   0.   ]
 [0.    0.25  0.    0.75 ]]
Lambda Diag Matrix @ Adjacenty Matrix = 
[[0.225  0.45   0.     0.0225]
 [0.03   0.03   0.03   0.    ]
 [0.     0.     0.09   0.    ]
 [0.     0.025  0.     0.075 ]]
Last opnion vector:
[0.9 0.1 0.9 0.1]
Lambda Diag Matrix @ Adjacenty Matrix @ Last opnion vector =
[0.24975 0.057   0.081   0.01   ]
Identity Matrix: 
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Invers of Lam:
[[0.1 0.  0.  0. ]
 [0.  0.9 0.  0. ]
 [0.  0.  0.1 0. ]
 [0.  0.  0.  0.9]]
Initial Opnion:
[0.9 0.1 0.9 0.1]
(I - Lam)@x0 = [0.09 0.09 0.09 0.09]
Finally we take the sum of [0.24975 0.057   0.081   0.01   ] + [0.09 0.09 0.09 0.09] = 
[0.33975 0.147   0.171   0.1    ]
Executing first step of Friedkin-Johnson model:
 [[0.9     0.33975]
 [0.1     0.147  ]
 [0.9     0.171  ]
 [0.1  

In [ ]:
# Question 4
##############################################################################################
# Part (b)

# Q: Where do we find values that are the most different opnions when passed different susbtibaliity 
#    values we call lambda.