In [ ]:
import numpy as np

In [ ]:
A = np.array([[.99,0,.01],
              [0.5,0.5,0],
              [0.5,0.5,0]])
A

array([[0.99, 0.  , 0.01],
       [0.5 , 0.5 , 0.  ],
       [0.5 , 0.5 , 0.  ]])

In [ ]:
A@A

array([[0.9851, 0.005 , 0.0099],
       [0.745 , 0.25  , 0.005 ],
       [0.745 , 0.25  , 0.005 ]])

In [ ]:
np.linalg.matrix_power(A,10)

array([[0.9804078 , 0.00978796, 0.00980424],
       [0.97960988, 0.01060216, 0.00978796],
       [0.97960988, 0.01060216, 0.00978796]])

In [ ]:
A2 = np.array([[1,0,0],
               [0.01,0.9,0.09],
               [0,0,1]])

In [ ]:
np.linalg.matrix_power(A2,1000)

array([[1.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [1.00000000e-01, 1.74787125e-46, 9.00000000e-01],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00]])

In [ ]:
A3 = np.array([[0.9,0,.1],
               [.8,.2,0],
               [0,.4,.6]])
A3

array([[0.9, 0. , 0.1],
       [0.8, 0.2, 0. ],
       [0. , 0.4, 0.6]])

In [ ]:
np.linalg.matrix_power(A3,1000)*11

array([[8., 1., 2.],
       [8., 1., 2.],
       [8., 1., 2.]])

In [ ]:
w = np.array([[8,1,2]]).T/11
w

array([[0.72727273],
       [0.09090909],
       [0.18181818]])

In [ ]:
w.T@A3

array([[0.72727273, 0.09090909, 0.18181818]])

NameError: ignored